### ISSUE TITLE
Разное расписание в приложении и на виджете.

### ISSUE THREAD

**Issue by ghost** [0niel/university-app#254]
**Описание ошибки**
Различное расписание в приложении и на виджете.

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Установить на экране виджет Ninja Mirea.
2. Можно будет заметить баг, что иногда расписание в приложении и на виджете разные(Скриншоты ниже).

**Ожидаемое поведение**
Одинаковое расписание в приложении и на виджете.

**Скриншоты**
![photo_2022-10-17_10-15-08](https://user-images.githubusercontent.com/79355695/196112826-44ef5cc6-2f97-4955-9b8e-64a6da9df840.jpg)
![photo_2022-10-17_10-15-08 (2)](https://user-images.githubusercontent.com/79355695/196112875-60f3a415-5956-49f6-99c9-cf7456ec7346.jpg)

**Смартфон:**
 - Девайс: Redmi Note 8 Pro
 - OS: Android | MIUI Global 12.5.8
 - Браузер: Chrome
 - Версия Android 11

**Дополнительно**
Если не сможете воспроизвести или обнаружить этот баг, то есть предположение, что это проблемы оболочки MIUI, она крайне ужасно работает с виджетами.

**Comment by ArthurLokhov** [comment]
Есть такая гипотеза, что выводится расписание другой группы, ибо данная ситуация опять повторяется. (Скриншоты ниже)
![1](https://user-images.githubusercontent.com/79355695/196342986-b0c764d7-8275-4dfa-9ea0-fd5c61776c02.jpg)
![2](https://user-images.githubusercontent.com/79355695/196342988-f1b05cf4-33f7-40f4-9488-f03d5dbc8e36.jpg)
Вероятно, что в приложении выводится расписание той группы, которую я указал, а на виджете выводится какое-то дефолтное значение. Но опять же это лишь гипотеза.
