### ISSUE TITLE
Постоянное перекидывание в настройки | IOS

### ISSUE THREAD

**Issue by jottyVlad** [0niel/university-app#380]
**Описание ошибки**
Постоянное перекидывание в настройки при авторизации в аккаунт / выборе группы. 
Когда можно было войти в профиль, то при входе перекидывало. Сейчас при выборе группы

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Добавьте расписание по какой-то группе
2. Группа добавится, но перекинет в настройки Mirea Ninja на самом Айфоне (не внутри приложения)

**Ожидаемое поведение**
Автоматический переход в настройки ниндзи на Айфоне.

**Смартфон:**
 - Девайс: iPhone Xr
 - OS: iOS 17.4

**Comment by 0niel** [comment]
Возможно, это поведение связано с установкой группы в качестве категории для FCM для получения пуш уведомлений об изменении в расписании. Репозиторий уведомлений должен запрашивать разрешение и открывать настройки, если разрешения на уведомления нет. Какие конкретно настройки в iOS открываются?

У меня iPhone, но я не могу воспроизвести проблему.

Вот недавно добавленная логика:

https://github.com/0niel/university-app/blob/2b0fb5fdc2e9714eee9265d08b99e782be513554/lib/schedule/view/schedule_page.dart#L75C6-L82C11

**Comment by jottyVlad** [comment]
Прочитал комментарий про пуши - действительно, если указать доступ к пушам, то проблема магически исчезает. Просто нигде не указывается, что приложению нужны пуши, и ты не понимаешь, с чего открываются настройки и что ему нужно. 

А проблеме этой много месяцев, только сейчас руки дошли ишью написать. 
![photo_2024-03-12_06-43-28](https://github.com/0niel/university-app/assets/44094832/21d673d3-ad02-4e54-adcc-67f7ec7c1748)

**Comment by 0niel** [comment]
Спасибо. Исправлено в последнем обновлении.
